### PR TITLE
JWT token refresh fixes

### PR DESCRIPTION
**Pull request by martinhladil**
I'm not sure if refreshing token for JWT is designed to work that way, but this is working for me very well.

### CODE REVIEW

**Comment by SLMaxwell** [comment]
Very nice find. I too had found and changed the 'with_auto_token_refresh' within client.rb to correct the JWT auth refresh.

My changes were exactly the same as yours. 

Only commenting here to give you a +1 and hopefully to push the pull request through to master faster.

Kudos.

**Comment by cburnette** [comment]
Thanks guys, I'll take a look at this soon. 

Chad

**Comment by cburnette** [comment]
Hey, thanks for the PR but I'm not sure what this is addressing.  For JWT the method is already automatically retrieving a new token (either user or admin).  See lines 223 and 226 of client.rb.  For JWT it's not necessary to register a callback as you don't need to persist the new tokens.  For non-JWT (i.e. OAuth2 with refresh tokens) it's necessary to store the refresh token, and hence the callback.

**Comment by martinhladil** [comment]
First, thank you both for looking into this. Second, I have very little knowledge how this is supposed to work, therefore sorry for my brief PR description.

My use case is simple. App which I'm working on acts like a middle man between users and actual Box app users. My app users typically performs a lot of subsequent actions which requires accessing Box API and it seems to be reasonable to store access token between these requests to improve performance as all Box API calls are slow.

This is how I construct box client in a user model:

```ruby
def box_client
  unless box_access_token
    update_column(:box_access_token, Boxr::get_user_token(box_id).access_token)
  end
  @box_client ||= Boxr::Client.new(box_access_token, as_user: box_id) do |access_token|
    update_column(:box_access_token, access_token)
  end
end
```

I'm open to suggestions how this could be done better.

**Comment by martinhladil** [comment]
And even without calling any callback there is a clear typo on client.rb line 210 which prevents to retrieve a new token because @jwt_secret_key simply doesn't exist.

**Pull request closed without merging**
