### PR TITLE
Client credentials grant

### PR DESCRIPTION
**Pull request by chernesk**
Hello.

In response to this issue: https://github.com/cburnette/boxr/issues/114 I'd like to have you look over this PR and let me know if it works for you and if it would be possible for it to get merged and versioned. 

If there are other changes you'd like to see before merging it, I'd be glad to make them.

Thank you!

### CODE REVIEW

**Review by xhocquet — CHANGES_REQUESTED** [review]
Hey @chernesk , thanks for the contribution!

This is looking pretty good to me, but a couple suggestions to get this merged - 
1. In the spec file, to follow existing patterns, I think you could just add another few calls below the existing ones with a comment specifying that this is testing the 'client credentials' OAuth grant type
2. Add an example to the README for this new ability, with a clear comment that it's for the 'client credentials' OAuth grant type

I think that should do it!

**Comment by chernesk** [comment]
> Hey @chernesk , thanks for the contribution!
> 
> This is looking pretty good to me, but a couple suggestions to get this merged -
> 
> 1. In the spec file, to follow existing patterns, I think you could just add another few calls below the existing ones with a comment specifying that this is testing the 'client credentials' OAuth grant type
> 2. Add an example to the README for this new ability, with a clear comment that it's for the 'client credentials' OAuth grant type
> 
> I think that should do it!

Thank you. I'll get on that. Getting the specs to run, even with what is in the main spec file has proved problematic for me. I'm glad to redo the spec with it making the call "live" to box. I'll resubmit the PR as soon as I can get the specs working.

**Comment by chernesk** [comment]
Hello. I'm trying to get the test to work. I've followed all of the steps, I believe, in `spec/boxr_spec.rb` to create the app in box and to give it the correct permissions. I'm still getting this when I run the tests:

`  19) zip downloads operations invokes zip downloads operations
      Failure/Error: raise BoxrError.new(status: res.status, body: res.body, header: res.header)
      
      Boxr::BoxrError:
        401: Bearer realm="Service", error="invalid_token", error_description="The access token provided is invalid."
      # ./lib/boxr/client.rb:139:in `get_all_with_pagination'
      # ./lib/boxr/folders.rb:35:in `folder_items'
      # ./lib/boxr/folders.rb:45:in `root_folder_items'
      # ./spec/spec_helper.rb:15:in `block (2 levels) in <top (required)>'
`

I've granted it everything and approved the app. Can you give me a pointer to what I may be doing wrong?

**Comment by xhocquet** [comment]
Thanks @chernesk , apologies that the test setup is a bit painful. It does rely on the Box developer account and a couple of secret keys added in your local env. But looks like you got it! I'll give it a spin on my end and get this merged 🎉

**Comment by xhocquet** [comment]
Hey @chernesk , I was able to get the new test to pass locally 👍🏻 

Since we are now testing the real response from Box is accurate, can we remove the extra test that was added titled 
`describe 'additional_fields'`? Seems like it would be duplicate testing at this point

**Comment by chernesk** [comment]
I'll do that. Sorry that I forgot to remove. I'll do that when I get home tonight.

**Comment by chernesk** [comment]
@xhocquet Thank you for bringing the extra test to my attention. I had planned to remove it, but missed that in the commit. I have removed it.

Thank you for your patience.

**Comment by xhocquet** [comment]
@chernesk not at all, thanks for addressing my feedback and for your work! This is good to go, and I'll cut a release sometime soon. There's a couple of other items in the issues/PRs that I wanted to check out first

**Comment by Stephanie-FDI** [comment]
Hello, I was wondering when this change might included in a release? I'd love to use the client credentials grant via Boxr rather than using a custom method. Thank you!

**Comment by xhocquet** [comment]
Just pushed that out, should be available via bundler!

**Comment by Stephanie-FDI** [comment]
> Just pushed that out, should be available via bundler!

Great, thank you!

**Pull request merged**
