### PR TITLE
add support for representations

### PR DESCRIPTION
**Pull request by Band-Aid**

### CODE REVIEW

**Comment by david-mccullars** [comment]
👍

**Comment by jordanfowler** [comment]
+1 👍

**Comment by Band-Aid** [comment]
oh shoot. i didnt notice i was committing other changes to this branch. I'll resubmit this pull request 
 again with the changes limited to representations.

**Comment by bheeshmar** [comment]
@Band-Aid - I can't find another PR with the representations changes. Did you create one?

**Comment by Band-Aid** [comment]
@bheeshmar 
I've been a bit lazy... Just submitted
https://github.com/cburnette/boxr/pull/55

**Pull request closed without merging**
